name: GitHub Actions Runner
version: "0.1.2"
slug: github-runner
description: Self-hosted GitHub Actions runner used to deploy the NetDaemon add-on
url: https://github.com/makabie/ha
arch:
  - amd64
  - aarch64
init: false
hassio_api: true
hassio_role: manager
map:
  - homeassistant_config:rw
options:
  repo: "makabie/ha"
  github_pat: ""
  runner_name: "homeassistant"
  ha_token: ""
schema:
  repo: str
  github_pat: password
  runner_name: str
  ha_token: password
